<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"themesettingsaddtocart": {}
		}
	}
</script>
<script type="text/javascript">
	require([
		'jquery',
		"Field_Themesettings/js/jquery.fancybox.pack",
		'Magento_Customer/js/customer-data'
		],
		function(customerData){
			jQuery(document).ready(function($) {
				jQuery(document).on("click", ".fieldthemesettings-fancybox", function(){
					var config = {};
					if(jQuery(this).data('fancybox-height')){
						config['minHeight'] = jQuery(this).data('fancybox-height');
						config['height'] = jQuery(this).data('fancybox-height');
					}
					if(jQuery(this).data('fancybox-width')){
						config['minWidth'] = jQuery(this).data('fancybox-width');
						config['width'] = jQuery(this).data('fancybox-width');
					}
					if(jQuery(this).data('fancybox-type')){
						config['type'] = jQuery(this).data('fancybox-type');
					}
					if(jQuery(this).data('fancybox-overlay-color')){
						config['overlayColor'] = jQuery(this).data('fancybox-overlay-color');
					}
					if(jQuery(this).data('fancybox-overlay-show')){
						config['overlayShow'] = jQuery(this).data('fancybox-overlay-show');
					}
					if(jQuery(this).data('fancybox-padding')){
						config['padding'] = jQuery(this).data('fancybox-padding');
					}
					if(jQuery(this).data('fancybox-margin')){
						config['margin'] = jQuery(this).data('fancybox-margin');
					}
					if(jQuery(this).data('fancybox-easing-in')){
						config['easingIn'] = jQuery(this).data('fancybox-easing-in');
					}
					if(jQuery(this).data('fancybox-easing-out')){
						config['easingOut'] = jQuery(this).data('fancybox-easing-out');
					}
					if(jQuery(this).data('fancybox-auto-size')){
						config['autoSize'] = jQuery(this).data('fancybox-auto-size');
					}
					if(jQuery(this).attr('href')){
						config['href'] = jQuery(this).attr('href');
					}
					if(jQuery(this).data('fancybox-href')){
						config['href'] = jQuery(this).data('fancybox-href');
					}
					config['helpers'] = {
						overlay: {
							locked: false
						}
					}
					if($(window).width()<768){
						var pHref = jQuery(this).data('fancybox-href');
						pHref = pHref + 'is_redirect/true';
						window.location = pHref;
						return false;
					}
					// Update Minicart
					config['afterClose'] = function(){
						$.ajax({
							url: "<?php echo $this->helper('Field\Themesettings\Helper\Data')->getRefreshCartUrl() ?>",
							type: 'post',
							dataType: 'json',
							beforeSend: function() {
								$('[data-block="minicart"]').trigger('contentLoading');
							},
							success: function(res) {
								$('[data-block="minicart"]').trigger('contentUpdated');
							}
						});
					}
					jQuery.fancybox.open(config);
				return false;
			});
                        jQuery(".field-widget .block-title").each( function(){
                                var element = $(this),
                                    element_parent = element.parent(),
                                    element_text = element.find('strong'),
                                    element_text_width = element_text.width(),
                                    element_button_margin = Math.round(element_text_width/2 + 25, 2);
                                element_parent.find('.owl-nav .owl-prev').css({'margin-right': element_button_margin});
                                element_parent.find('.owl-nav .owl-next').css({'margin-left': element_button_margin});
                        });
                        jQuery(".product-thumblist img").hover(function(){
                                var element = $(this),
                                    element_parent = element.closest(".product-image"),
                                    element_src = element.attr("src");
                                element_parent.find(".product-item-photo img, .hover-image img").attr("src", element_src);
                        });
		});
	});
</script>