<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$data = $this->helper('Field\Themesettings\Helper\Data'); 
$field = $this->helper('Field\Themesettings\Helper\Theme');
$status = $field->getPopupCfg('popup_new/status');
$title = $field->getPopupCfg('popup_new/popup_title');
$content = $field->getPopupCfg('popup_new/popup_content');
$cmsblock = $field->getPopupCfg('popup_new/static_block');
$popup_width = $field->getPopupCfg('popup_new/popup_width');
$popup_height = $field->getPopupCfg('popup_new/popup_height');
$auto_middle = $field->getPopupCfg('popup_new/auto_middle');
$cookie_time = (int)$field->getPopupCfg('popup_new/cookie_time');
$top = 120; 
$speed= 500; 

$html = "";
if($cmsblock != ''){
    $html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $data->filter($html);

if ($status){
?>
<div id="newsletter_pop_up" class="newsletterpopup">
	<div class="btn-close newletter_popup_close"></div>
	<div class="content">
                <?php if ($title != ""){ ?>
                        <div class="title"><?php echo $title; ?></div>
                <?php } ?>
                <?php if ($html != ""){  echo $content;  } ?>
                <?php if ($content != ""){ ?>
                        <div class="des-newletter"><?php echo $content; ?></div>
                <?php } ?>
                <form class="form subscribe"
                        novalidate
                        action="<?php echo $block->getFormActionUrl() ?>"
                        method="post"
                        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                        id="newsletter-validate-details">
                        <div class="field newsletter">
                                <div class="control">
                                        <input name="email" type="email" id="newsletters"
                                                                placeholder="<?php /* @escapeNotVerified */ echo __('Your e-mail') ?>"
                                                                data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                        </div>
                        <div class="actions">
                                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                                        <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                                </button>
                        </div>
                </form>
               
	</div>
	 <div class="subscribe-bottom">
	 	<span>
                        <input type="checkbox" id="newsletter_popup_dont_show_again"></span>
                        <label for="newsletter_popup_dont_show_again"><?php echo __("Don't show this popup again")?></label>
                </div>
</div>
<script type ="text/javascript">
require(["jquery"], function($){
		function setCookie(name,value,days)
		{
		  if (days) {
				var date = new Date();
				date.setTime(date.getTime()+(days*24*60*60*1000));
				var expires = "; expires="+date.toGMTString();
			  }
			  else var expires = "";
			  document.cookie = name+"="+value+expires+"; path=/";
		}

		function getCookie(name)
		{
			  var nameEQ = name + "=";
			  var ca = document.cookie.split(';');
			  for(var i=0;i < ca.length;i++) {
				var c = ca[i];
				while (c.charAt(0)==' ') c = c.substring(1,c.length);
				if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
			  }
			  return null;
		}
			
                <?php if($auto_middle || $top == "") $top = 'auto'; ?>
		if(getCookie("shownewsletter") != 1){
			var pPopup = $('#newsletter_pop_up').bPopup({
				position: ['auto', <?php echo "'".$top."'"; ?>],
                                positionStyle: 'fixed',
				speed: <?php if($speed != '') echo $speed; else echo '450' ?>,
				transition: 'slideDown',
				onClose: function() { setCookie("shownewsletter",'1',<?php if($cookie_time!='') echo $cookie_time;else echo '1' ?>); 
				}
			});
			$('.newletter_popup_close').on('click', function(){
				pPopup.close();
			}); 
		}
			
		$( "#newsletter_pop_up form" ).submit(function( event ) {
				setCookie("shownewsletter",'1',<?php if($cookie_time!='') echo $cookie_time;else echo '1' ?>);
		});
		
		$('#newsletter_popup_dont_show_again').on('change', function(){
			if(getCookie("shownewsletter") != <?php if($cookie_time!='') echo $cookie_time;else echo '1' ?>){   
				setCookie("shownewsletter",'1',<?php if($cookie_time!='') echo $cookie_time;else echo '1' ?>)
			}else{
				setCookie("shownewsletter",'0',<?php if($cookie_time!='') echo $cookie_time;else echo '1' ?>)
			}
		}); 
			

 });	 
</script>
<?php  } ?>